modLoader="javafml"
loaderVersion="[52,)"
license="All rights reserved"
[[mods]]
modId="pinchat"
version="${file.jarVersion}"
displayName="Pinchat Mod"
description='''Pinchat Mod'''

[[dependencies.pinchat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"

[[dependencies.pinchat]]
    modId="forge"
    mandatory=true
    versionRange="[52,)"
    ordering="NONE"
    side="BOTH"
